### ISSUE TITLE
Remove .env file

### ISSUE THREAD

**Issue by mattonit** [Rotarepmi/MyScrum_API#1]
GitHub in their best practices ([here's an example](https://github.com/github/gitignore/blob/master/Node.gitignore) .env file recommended by GitHub) recommends putting the .env file in the .gitignore. This should be removed from your repository as it might contain some sensitive information (such as JWT Secret ;) )

**Comment by Rotarepmi** [comment]
Thanks,

forgot to add to .gitignore
